// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// readcols
Rcpp::CharacterMatrix readcols(std::string fn, std::vector<int> colsel, size_t nFirstSkipLines, size_t nSkipUnit);
RcppExport SEXP manqq_readcols(SEXP fnSEXP, SEXP colselSEXP, SEXP nFirstSkipLinesSEXP, SEXP nSkipUnitSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< std::string >::type fn(fnSEXP );
        Rcpp::traits::input_parameter< std::vector<int> >::type colsel(colselSEXP );
        Rcpp::traits::input_parameter< size_t >::type nFirstSkipLines(nFirstSkipLinesSEXP );
        Rcpp::traits::input_parameter< size_t >::type nSkipUnit(nSkipUnitSEXP );
        Rcpp::CharacterMatrix __result = readcols(fn, colsel, nFirstSkipLines, nSkipUnit);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
